In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [4]:
df.describe(include = 'all')

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [5]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [6]:
# Edit columns names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(f'new columns is: {df.columns.to_list()}')

new columns is: ['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent', 'payment_method', 'location', 'transaction_date']

In [7]:
# Convert ERROR and UNKNOWN to NaN
cleanup_map = {
    'ERROR' : np.nan,
    'UNKNOWN' : np.nan,
}

df = df.replace(cleanup_map)

In [8]:
# Convert the datatype for this columns
df['quantity'] = pd.to_numeric(df['quantity'], errors = 'coerce')
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors = 'coerce')
df['total_spent'] = pd.to_numeric(df['total_spent'], errors = 'coerce')
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors = 'coerce')

In [9]:
df.head(20)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  str
 1   item              9031 non-null   str
 2   quantity          9521 non-null   float64
 3   price_per_unit    9467 non-null   float64
 4   total_spent       9498 non-null   float64
 5   payment_method    6822 non-null   str
 6   location          6039 non-null   str
 7   transaction_date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

In [11]:
df.isnull().sum()

transaction_id         0
item                 969
quantity             479
price_per_unit       533
total_spent          502
payment_method      3178
location            3961
transaction_date     460
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['transaction_id'].duplicated().sum()

np.int64(0)

In [14]:
(df['quantity'] <= 0).sum()

np.int64(0)

In [15]:
(df['price_per_unit'] <= 0).sum()

np.int64(0)

In [16]:
(df['total_spent'] <= 0).sum()

np.int64(0)

In [17]:
mask = (df['quantity'] * df['price_per_unit'] != df['total_spent'])
print(df.loc[mask, 'transaction_id'])

2       TXN_4271903
20      TXN_3522028
25      TXN_7958992
31      TXN_8927252
42      TXN_6650263
           ...
9984    TXN_3142496
9988    TXN_9594133
9993    TXN_4766549
9996    TXN_9659401
9998    TXN_7695629
Name: transaction_id, Length: 1456, dtype: str

In [18]:
price_map = {
    'Cake' : 3.0,
    'Coffee' : 2.0,
    'Cookie' : 1.0,
    'Juice' : 3.0,
    'Salad' : 5.0,
    'Sandwich' : 4.0,
    'Smoothie' : 4.0,
    'Tea' : 1.5
}
df['price_per_unit'] = df['price_per_unit'].fillna(df['item'].map(price_map))

In [19]:
price_map_for_item = {
    'Coffee' : 2.0,
    'Cookie' : 1.0,
    'Salad' : 5.0,
    'Tea' : 1.5
}
item_map = {v: k for k,v in price_map_for_item.items()}
df['item'] = df['item'].fillna(df['price_per_unit'].map(item_map))

In [20]:
df.loc[df['quantity'].isna(), 'quantity'] = (df['total_spent'] / df['price_per_unit'])
df.loc[df['price_per_unit'].isna(), 'price_per_unit'] = (df['total_spent'] / df['quantity'])
df.loc[df['total_spent'].isna(), 'total_spent'] = (df['quantity'] * df['price_per_unit'])

In [21]:
df.isnull().sum()

transaction_id         0
item                 501
quantity              23
price_per_unit         6
total_spent           23
payment_method      3178
location            3961
transaction_date     460
dtype: int64

In [22]:
df['transaction_date'].describe()

count                          9540
mean     2023-07-01 23:00:31.698113
min             2023-01-01 00:00:00
25%             2023-04-01 00:00:00
50%             2023-07-02 00:00:00
75%             2023-10-02 00:00:00
max             2023-12-31 00:00:00
Name: transaction_date, dtype: object

In [23]:
print(df.loc[df['quantity'].isna(), 'quantity'])

236    NaN
278    NaN
641    NaN
738    NaN
2796   NaN
3203   NaN
3224   NaN
3401   NaN
3779   NaN
4257   NaN
5841   NaN
7029   NaN
7297   NaN
7597   NaN
8021   NaN
8443   NaN
8465   NaN
8479   NaN
8574   NaN
8732   NaN
9590   NaN
9819   NaN
9869   NaN
Name: quantity, dtype: float64

In [24]:
print(df.loc[df['price_per_unit'].isna(), 'price_per_unit'])

1761   NaN
2289   NaN
3779   NaN
4152   NaN
7597   NaN
9819   NaN
Name: price_per_unit, dtype: float64

In [25]:
df.head(70)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
65,TXN_4987129,Sandwich,3.0,4.0,12.0,NaN,In-store,2023-10-20
66,TXN_8501819,Juice,2.0,3.0,6.0,Cash,NaN,2023-03-30
67,TXN_3068204,Cookie,1.0,1.0,1.0,Credit Card,Takeaway,2023-10-03
68,TXN_8427104,Salad,2.0,5.0,10.0,NaN,In-store,2023-10-27
69,TXN_8471743,NaN,5.0,3.0,15.0,Digital Wallet,In-store,2023-04-06

In [26]:
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [27]:
#print(df.loc[:, df['item']])

In [28]:
df['item'].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
 'Sandwich',      'Tea',    'Juice']
Length: 9, dtype: str

In [29]:
df.isnull().sum()

transaction_id         0
item                 501
quantity              23
price_per_unit         6
total_spent           23
payment_method      3178
location            3961
transaction_date     460
dtype: int64

In [30]:
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [31]:
print(df.shape)
print(df.isna().mean() * 100)

(10000, 8)
transaction_id       0.00
item                 5.01
quantity             0.23
price_per_unit       0.06
total_spent          0.23
payment_method      31.78
location            39.61
transaction_date     4.60
dtype: float64

In [32]:
#fill category columns with the value 'Unknown'
category_columns = df.select_dtypes(include = ['str']).columns
for column in category_columns:
    df[column] = df[column].fillna('Unknown')

In [33]:
df.dropna(subset = ['quantity', 'price_per_unit', 'total_spent','transaction_date'], inplace = True)

In [34]:
df.isnull().sum()

transaction_id      0
item                0
quantity            0
price_per_unit      0
total_spent         0
payment_method      0
location            0
transaction_date    0
dtype: int64

In [35]:
df.shape

(9514, 8)

In [36]:
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unknown,Unknown,2023-08-30
9996,TXN_9659401,Unknown,3.0,1.0,3.0,Digital Wallet,Unknown,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Unknown,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,Unknown,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [37]:
df.to_csv('cleaned_cafe_sales.csv', index=False)